eggjs/core

- README.md
- package.json
doc
http://stackoverflow.com/questions/18435564/the-difference-between-extensible-and-pluggable-applications
> doc: Plugable > Pluggable

- test/utils/index.test.js
> test: fix homedir testcase on Windows

- lib/loader/egg_loader.js
- test/loader/get_server_env.test.js
https://github.com/eggjs/egg-core/pull/23#issuecomment-254717826
> feat: [BREAKING_CHANGE] env as prod when EGG_SERVER_ENV undefined & NODE_ENV prod

- lib/loader/mixin/custom.js
- package.json
- test/fixtures/custom-app-generator/app.js
- test/fixtures/custom-app-generator/package.json
- test/loader/mixin/load_custom_app.test.js
> feat: app support export generator

- lib/loader/egg_loader.js
- test/fixtures/framework-wrong-eggpath/index.js
- test/fixtures/framework-wrong-eggpath/package.json
- test/loader/get_framework_paths.test.js
EggLoader
If define a method by mistake, it will throw an unknow error.
Closes eggjs/egg#126
> refactor: assert eggPath should be string

- lib/loader/mixin/plugin.js
- test/fixtures/egg/config/plugin.js
- test/fixtures/egg/plugins/zzz/package.json
- test/fixtures/load-plugin-config-override/config/plugin.js
- test/fixtures/load-plugin-config-override/package.json
- test/fixtures/load-plugin-config-override/plugins/zzz/package.json
- test/fixtures/noplugin/config/plugin.js
- test/loader/get_load_units.test.js
- test/loader/mixin/load_plugin.test.js
pluginLoader
Closes eggjs/egg#125
> feat: warn when redefine plugin

- package.json
> chore: add pkg.files

- lib/loader/mixin/middleware.js
- package.json
- test/fixtures/middleware-app-disable/app/middleware/custom.js
- test/fixtures/middleware-app-disable/app/middleware/static.js
- test/fixtures/middleware-app-disable/config/config.js
- test/fixtures/middleware-app-disable/package.json
- test/fixtures/middleware-disable/app/middleware/custom.js
- test/fixtures/middleware-disable/app/middleware/static.js
- test/fixtures/middleware-disable/config/config.js
- test/fixtures/middleware-disable/package.json
- test/fixtures/middleware-ignore/app/middleware/custom.js
- test/fixtures/middleware-ignore/app/middleware/static.js
- test/fixtures/middleware-ignore/config/config.js
- test/fixtures/middleware-ignore/package.json
- test/fixtures/middleware-match/app/middleware/custom.js
- test/fixtures/middleware-match/app/middleware/static.js
- test/fixtures/middleware-match/config/config.js
- test/fixtures/middleware-match/package.json
- test/fixtures/middleware-redefined/app/middleware/custom.js
- test/fixtures/middleware-redefined/app/middleware/static.js
- test/fixtures/middleware-redefined/config/config.js
- test/fixtures/middleware-redefined/package.json
- test/loader/mixin/load_middleware.test.js
> feat: core middlewares support enable/match/ignore options

- lib/loader/mixin/middleware.js
> refactor: don't use core middleware when enable = false

- lib/loader/mixin/middleware.js
- test/loader/mixin/load_middleware.test.js
> feat: make app middlewares also support enable

- lib/loader/context_loader.js
- test/fixtures/context-loader/app/router.js
- test/fixtures/context-loader/app/service1/user.js
- test/fixtures/context-loader/app/service2/user.js
- test/fixtures/egg/index.js
- test/loader/context_loader.test.js
> fix: distinguish property cache

- lib/loader/mixin/plugin.js
- package.json
- test/egg.test.js
- test/loader/egg_loader.test.js
- test/loader/file_loader.test.js
- test/loader/get_app_info.test.js
- test/loader/get_appname.test.js
- test/loader/get_framework_paths.test.js
- test/loader/get_load_units.test.js
- test/loader/get_server_env.test.js
- test/loader/load_file.test.js
- test/loader/mixin/load_agent_extend.test.js
- test/loader/mixin/load_application_extend.test.js
- test/loader/mixin/load_config.test.js
- test/loader/mixin/load_custom_agent.test.js
- test/loader/mixin/load_custom_app.test.js
- test/loader/mixin/load_extend.test.js
- test/loader/mixin/load_middleware.test.js
- test/loader/mixin/load_plugin.test.js
- test/loader/mixin/load_service.test.js
- test/utils/index.test.js
- test/utils/router.test.js
> refactor: warn only for redefine the same package

- lib/loader/mixin/config.js
- test/loader/mixin/load_config.test.js
conflict with https://github.com/eggjs/egg/pull/231
> fix: don't assert config.proxy

- .gitignore
- lib/egg.js
- test/egg.test.js
- test/fixtures/app-before-close/app.js
> fix: execute beforeClose hooks in reverse order

- lib/utils/base_context_class.js
- test/fixtures/context-loader/app/pathname/a/b/c.js
- test/fixtures/context-loader/app/router.js
- test/loader/context_loader.test.js
> feat: add this.config in BaseContextClass

- lib/utils/base_context_class.js
- test/fixtures/context-loader/app/router.js
- test/fixtures/context-loader/app/service/post.js
- test/fixtures/context-loader/app/service/user.js
- test/loader/context_loader.test.js
> feat: add this.service in BaseContextClass

- lib/utils/index.js
file loader
fix test on windows
> test: fix test on windows

- lib/egg.js
- test/egg.test.js
- test/fixtures/beforestart-params-error/app.js
- test/fixtures/beforestart/app.js
app.beforeStart 
app.beforeStart support async function same as beforeClose
> feat: app.beforeStart support async function same as beforeClose

- lib/loader/mixin/controller.js
- test/fixtures/async-controller-app/app/controller/async.js
- test/fixtures/async-controller-app/package.json
- test/loader/mixin/load_controller.test.js
controller
`module.exports = async ctx => {}` 形式的 controller 直接报错。
> feat: imporve error message of async controller

- lib/egg.js
- package.json
- test/egg.test.js
> fix: make sure close once

- package.json
- test/egg.test.js
https://github.com/eggjs/egg/issues/331
> feat: [BREAKING_CHANGE] can get error from .ready()

- lib/loader/context_loader.js
- test/fixtures/service-unique/app/controller/same.js
- test/fixtures/service-unique/app/router.js
- test/fixtures/service-unique/app/service/ctx.js
- test/fixtures/service-unique/package.json
- test/loader/mixin/load_service.test.js
> fix: context loader cache independent in each request

- lib/egg.js
- test/egg.test.js
- test/fixtures/extend-controller-service/app.js
- test/fixtures/extend-controller-service/app/controller/api.js
- test/fixtures/extend-controller-service/app/router.js
- test/fixtures/extend-controller-service/app/service/api.js
- test/fixtures/extend-controller-service/package.json
- egg.Service
- egg.Controller
> fix: define egg.Service and egg.Controller in constructor

- README.md
- lib/egg.js
- lib/loader/context_loader.js
- lib/loader/egg_loader.js
- lib/loader/file_loader.js
- lib/utils/base_context_class.js
- lib/utils/router.js
> docs: update jsdoc

- lib/egg.js
- lib/loader/egg_loader.js
- lib/loader/mixin/extend.js
- lib/utils/router.js
- test/egg.test.js
- test/fixtures/egg/config/plugin.js
- test/fixtures/egg/node_modules/package/package.json
- test/fixtures/no-core-middleware/package.json
- test/fixtures/no-helper/app/extend/helper.js
- test/fixtures/no-helper/package.json
- test/fixtures/noplugin/config/plugin.js
- test/fixtures/redefin-plugin/config/plugin.js
- test/fixtures/redefin-plugin/package.json
- test/fixtures/router-app/app/controller/package.js
- test/fixtures/router-app/app/router.js
- test/loader/get_load_units.test.js
- test/loader/mixin/load_config.test.js
- test/loader/mixin/load_helper_extend.test.js
- test/loader/mixin/load_plugin.test.js
- test/utils/index.test.js
- test/utils/router.test.js
router, EggCore
- fix error when instantiate EggCore
- fix named route when use regexp
> refactor: improve coverage

- lib/loader/file_loader.js
- lib/loader/mixin/controller.js
- lib/utils/index.js
- test/fixtures/load_dirs/inject/a.js
- test/fixtures/load_dirs/inject/b.js
- test/loader/file_loader.test.js
file_loader, load_controller
pathname can be got from properties, so don't parse from fullpath again
Closes https://github.com/eggjs/egg/issues/472
> fix: improve getPathName

- lib/loader/mixin/config.js
- package.json
- test/fixtures/config-array/config/plugin.js
- test/fixtures/config-array/package.json
- test/fixtures/config-array/plugin/a/config/config.default.js
- test/fixtures/config-array/plugin/a/package.json
- test/fixtures/config-array/plugin/b/config/config.default.js
- test/fixtures/config-array/plugin/b/package.json
- test/loader/mixin/load_config.test.js
Ref https://github.com/eggjs/egg/issues/500
> feat: [BREAKING_CHANGE] array will be overridden when load config

- test/fixtures/router-app/app/controller/async.js
- test/fixtures/router-app/app/middleware/generator_both.js
- test/fixtures/router-app/app/router.js
- test/utils/router.test.js
> test: add case for generator middleware with async controller

- lib/loader/mixin/plugin.js
> chore:typo

- lib/loader/mixin/controller.js
- test/fixtures/controller-app/app/controller/function_attr.js
- test/loader/mixin/load_controller.test.js
> feat: to keep controller function attributes

- index.js
- test/index.test.js
> feat: expose BaseContextClass

- lib/loader/mixin/plugin.js
expose these two for the `begg` to do check ensure that it's not allowed to overwrite the framwork's plugins.
> feat:expose appPlugins&customPlugins

- lib/utils/index.js
> fix: find the true callee bebind proxy

- test/loader/mixin/load_plugin.test.js
> test: add testcase for appPlugins and customPlugins

- .autod.conf
- lib/loader/mixin/extend.js
- test/fixtures/extend/app/controller/home.js
- test/fixtures/extend/app/extend/response.js
- test/loader/mixin/load_extend.test.js
> fix: allow extend setter or getter alone

- lib/utils/sequencify.js
- test/fixtures/egg/config/plugin.js
- test/fixtures/egg/node_modules/opt/package.json
- test/fixtures/plugin-optional-dependencies/config/plugin.js
- test/fixtures/plugin-optional-dependencies/node_modules/f/package.json
- test/loader/mixin/load_plugin.test.js
this plugin should be disabled, this PR will fix it.
> fix: optionally depend on a plugin which is disabled.

- lib/loader/mixin/plugin.js
- test/loader/mixin/load_plugin.test.js
- [] `npm test` passes
上次漏了这个eggPlugins，不保留不好搞校验
> feat: expose eggPlugins

- lib/loader/egg_loader.js
- lib/utils/index.js
- package.json
- test/loader/egg_loader.test.js
- test/utils/index.test.js
> refactor: export getHomedir that can be extended

- README.md
- lib/loader/file_loader.js
- test/loader/file_loader.test.js
Ref https://github.com/node-modules/loading/pull/32
> feat(file_loader): ignore option support array in FileLoader

- lib/loader/file_loader.js
- lib/loader/mixin/controller.js
- test/fixtures/controller-app/app/controller/admin/config.js
- test/fixtures/controller-app/app/router.js
- test/loader/mixin/load_controller.test.js
> feat: add fullPath property on class instance

- lib/egg.js
> [refactor] core: use es6 default parameter value synax.

- lib/loader/mixin/controller.js
- lib/loader/mixin/middleware.js
- lib/loader/mixin/service.js
- test/fixtures/other-directory/app/other-controller/user.js
- test/fixtures/other-directory/app/other-middleware/user.js
- test/fixtures/other-directory/app/other-service/user.js
- test/fixtures/other-directory/package.json
- test/loader/mixin/load_controller.test.js
- test/loader/mixin/load_middleware.test.js
- test/loader/mixin/load_service.test.js
loadController, loadMiddleware, loadService
- controller
- middleware
- service
> feat: support custom directory

- README.md
- lib/loader/file_loader.js
- test/fixtures/load_dirs/filter/arr.js
- test/fixtures/load_dirs/filter/class.js
- test/fixtures/load_dirs/filter/object.js
- test/loader/file_loader.test.js
> feat(file_loader): support filter options

- lib/loader/egg_loader.js
> [refactor] core: use es6 rest parameter.

- test/loader/file_loader.test.js
> test: fix the testcase that is skipped

- lib/egg.js
- lib/loader/egg_loader.js
- lib/loader/file_loader.js
- lib/loader/mixin/controller.js
- lib/loader/mixin/custom.js
- lib/loader/mixin/plugin.js
> chore(documentation): fix typo

- lib/utils/index.js
+ lib/utils/index.js
+ use template literals in lib/utils/index.js
> refactor: use template literals in lib/utils/index.js

- lib/loader/mixin/controller.js
- package.json
- test/fixtures/controller-app/app/controller/class.js
> fix: load class controller should skip getter & setter

- .travis.yml
> test: add node 8

- .eslintignore
- lib/loader/mixin/controller.js
- lib/utils/index.js
> chore: improve cov

- lib/loader/mixin/extend.js
> feat: framework can override getExtendFilePaths

- appveyor.yml
- lib/loader/mixin/plugin.js
- package.json
> refactor(plugin): ignore loop when push plugin.default.js

- README.md
- lib/egg.js
fix typo：
- wil  -> will
- `String|Array`  ->  `String/Array` 
- No `Application` method in `egg-core`
> docs: fix typo

- lib/loader/mixin/config.js
- test/fixtures/configmeta/config/config.js
- test/fixtures/configmeta/package.json
- test/loader/mixin/load_config.test.js
config
The configMeta has config structure, but the value is the filepath
which defines the config
> feat: generate configMeta

- lib/loader/mixin/extend.js
> style: spelling mistakes，orginal -> original

- lib/egg.js
- test/egg.test.js
> feat: add toPromise and toAsyncFunction

- lib/egg.js
- test/egg.test.js
> feat: toAsyncFunction compact with async function

- test/egg.test.js
- test/loader/context_loader.test.js
- test/loader/egg_loader.test.js
- test/loader/file_loader.test.js
- test/loader/get_app_info.test.js
- test/loader/get_appname.test.js
- test/loader/get_framework_paths.test.js
- test/loader/get_load_units.test.js
- test/loader/get_server_env.test.js
- test/loader/load_file.test.js
- test/loader/mixin/load_agent_extend.test.js
- test/loader/mixin/load_application_extend.test.js
- test/loader/mixin/load_config.test.js
- test/loader/mixin/load_controller.test.js
- test/loader/mixin/load_custom_agent.test.js
- test/loader/mixin/load_custom_app.test.js
- test/loader/mixin/load_extend.test.js
- test/loader/mixin/load_helper_extend.test.js
- test/loader/mixin/load_middleware.test.js
- test/loader/mixin/load_plugin.test.js
- test/loader/mixin/load_service.test.js
- test/utils/index.test.js
- test/utils/router.test.js
> test: use async function instead of generator function

- index.js
- lib/utils/index.js
- test/index.test.js
related https://github.com/eggjs/egg/issues/1679
> feat: export egg utils

- lib/loader/mixin/controller.js
- test/loader/mixin/load_controller.test.js
> feat: export controller function's FULLPATH

- lib/loader/mixin/controller.js
- test/fixtures/controller-app/app/controller/object.js
- test/fixtures/controller-app/app/router.js
- test/loader/mixin/load_controller.test.js
pick from https://github.com/eggjs/egg-core/pull/131
> feat: export controller function's FULLPATH (#131)

- lib/loader/mixin/controller.js
- test/fixtures/controller-app/app/controller/object.js
- test/fixtures/controller-app/app/router.js
- test/loader/mixin/load_controller.test.js
> fix: should add parent prefix

- .travis.yml
- appveyor.yml
- lib/loader/mixin/plugin.js
- package.json
- test/fixtures/plugin-dep-disable/plugins/a/package.json
- test/loader/mixin/load_plugin.test.js
> fix: adjust implicitly enable logic

- lib/utils/router.js
- test/utils/router.test.js
cause by https://github.com/eggjs/egg-core/pull/125/files#diff-8c3b17be5fc29672ba311e100af6bbacR316
Controller instance check will delay.
> fix: check whether controller exists

- lib/egg.js
- test/fixtures/router-in-app/app.js
- test/fixtures/router-in-app/app/middleware/foo.js
- test/fixtures/router-in-app/app/router.js
- test/fixtures/router-in-app/config/config.default.js
- test/fixtures/router-in-app/package.json
- test/utils/router.test.js
> fix: should load router middleware in beforeStart

- lib/egg.js
- test/fixtures/router-in-app/app.js
- test/fixtures/router-in-app/app/middleware/foo.js
- test/fixtures/router-in-app/app/router.js
- test/fixtures/router-in-app/config/config.default.js
- test/fixtures/router-in-app/package.json
- test/utils/router.test.js
> fix: should load router middleware in beforeStart (#139)

- lib/egg.js
- lib/loader/egg_loader.js
- test/egg.test.js
> feat: support options.serverScope for egg-mock

- lib/utils/router.js
- test/fixtures/router-app/app/router.js
- test/utils/router.test.js
https://github.com/eggjs/egg/issues/1944
> fix: router muti-path register (#1944).

- lib/loader/egg_loader.js
- lib/loader/mixin/extend.js
- test/egg.test.js
extract requireFile to loadFile without running function
> refactor: add timing to extend

- lib/loader/egg_loader.js
- test/fixtures/load_to_app/app/model/user.js
- test/fixtures/load_to_app/app/service/user.js
- test/fixtures/load_to_app/package.json
- test/loader/egg_loader.test.js
> fix: convert symbol to string

- lib/utils/timing.js
- test/egg.test.js
- test/fixtures/timing/app.js
- test/utils/timing.test.js
> fix: timing can be started multiple times

- lib/egg.js
> fix a typo

- README.md
- lib/egg.js
现在已经使用 env 来控制 ts 的加载，因此原先的 typescript 的入参可以移除了
> fix: remove useless code

- lib/loader/egg_loader.js
- lib/loader/mixin/plugin.js
- test/fixtures/egg/node_modules/package/package.json
- test/loader/get_load_units.test.js
close https://github.com/eggjs/egg/issues/2767
> feat: loadUnit should exports name

- index.d.ts
> chore(typings): add index.d.ts

- package.json
> chore(typings): add pkg.types and pkg.files entry for index.d.ts

- lib/loader/egg_loader.js
- package.json
- test/loader/get_load_units.test.js
https://github.com/eggjs/egg-core/pull/172
> revert: #172 loadUnit.name 

- .gitignore
- lib/loader/file_loader.js
- lib/utils/index.js
Use `sets` instead of `or` in reg is clearer to be understand.
`.idea` is created by the series of IDE which developed by JetBrains.
> style(core): beautify reg and add .idea to ignore

- lib/loader/mixin/custom.js
- test/egg.test.js
- test/fixtures/boot/app/plugin/boot-plugin-empty/app.js
- test/fixtures/boot/app/plugin/boot-plugin-empty/package.json
- test/fixtures/boot/config/plugin.js
> fix: app.js export can be non-function

- .eslintrc
eslint
stop looking for configure in parent folders
> chore(eslint) set root=true to stop looking in parent folders

- lib/lifecycle.js
- test/lifecycle.test.js
lifecycle
forbid adding hook atfter initialization
> fix(lifecycle): forbid adding hook atfter initialization

- benchmark/middleware/start.js
> resolve EggApplication is not a Class

- lib/loader/egg_loader.js
- lib/loader/mixin/router.js
- test/loader/egg_loader.test.js
> feat: loader support load file without extname

- lib/utils/router.js
- package.json
> chore: use @eggjs/router instead of koa-router

- lib/egg.js
- lib/loader/egg_loader.js
- test/loader/get_server_env.test.js
> feat: support options.env to specific server env

- package.json
> deps: use egg router 2.0.0

- index.d.ts
- package.json
- test/egg-ts.test.js
- test/fixtures/app-ts/app-error.ts
- test/fixtures/app-ts/app.ts
- test/fixtures/app-ts/tsconfig.json
- test/fixtures/load_dirs/package.json
将 egg 中的一些声明下沉到 egg-core 中，丰富 egg-core 中的声明，添加 `loadToApp` 等方法
> feat: improve d.ts

- lib/loader/mixin/custom_loader.js
- test/loader/mixin/load_custom_loader.test.js
> fix: customLoader should not overwrite the existing property

- lib/loader/mixin/custom_loader.js
- test/fixtures/custom-loader/app/util/sub/fn.js
- test/fixtures/custom-loader/app/util/test.js
- test/fixtures/custom-loader/config/config.default.js
- test/loader/mixin/load_custom_loader.test.js
https://github.com/eggjs/egg/issues/3547
> feat: custom loader support exports

- index.d.ts
EggLoader
correct the return type of `caseStyle`, [ref issue](https://github.com/eggjs/egg/issues/3618)
> fix: fix FileLoaderOption->caseStyle return type, fix #3618

- lib/loader/mixin/middleware.js
Usage:
```bash
DEBUG=egg-core:middleware egg-bin start
```
> feat: debug middleware enter log on every request

- lib/loader/egg_loader.js
- lib/loader/mixin/custom.js
- test/fixtures/boot-class/agent.js
- test/fixtures/boot-class/app.js
- test/fixtures/boot-class/package.json
- test/loader/mixin/load_custom_agent.test.js
- test/loader/mixin/load_custom_app.test.js
抛出有意义的错误，避免开发者使用到新的插件后信息错误。
来源：内网 mysql 插件问题。
> fix: app.js is not support class

- .travis.yml
- lib/egg.js
- lib/lifecycle.js
- lib/loader/context_loader.js
- lib/loader/egg_loader.js
- lib/loader/file_loader.js
- lib/loader/mixin/config.js
- lib/loader/mixin/custom.js
- lib/loader/mixin/extend.js
- lib/loader/mixin/middleware.js
- lib/loader/mixin/plugin.js
- lib/loader/mixin/router.js
- lib/loader/mixin/service.js
- lib/utils/base_context_class.js
- package.json
- test/egg.test.js
- test/fixtures/boot-timeout/app.js
- test/fixtures/boot-timeout/package.json
> fix: fix ready callback id

- .travis.yml
- lib/lifecycle.js
- test/egg.test.js
- test/fixtures/boot-before-close/app.js
- test/fixtures/boot-before-close/app/plugin/boot-plugin-dep/app.js
- test/fixtures/boot-before-close/app/plugin/boot-plugin-dep/package.json
- test/fixtures/boot-before-close/app/plugin/boot-plugin/app.js
- test/fixtures/boot-before-close/app/plugin/boot-plugin/package.json
- test/fixtures/boot-before-close/config/plugin.js
- test/fixtures/boot-before-close/package.json
LifeCycle
The order of beforeClose hook execute should be reverse of load units order.
> fix: fix before close order

- index.d.ts
- ~~`npm test` passes~~
- ~~tests and/or benchmarks are included~~
- ~~documentation is changed or added~~
No
主要添加一些遗漏的方法或者属性的接口定义，不然 midway 那边就一直会报错。
> chore(typings): add EggLoader interface

- index.d.ts
egg-core(Typescript)
修复 #221 导致的错误
> fix: 修复 loader 类型错误

- .travis.yml
- lib/utils/timing.js
- test/utils/timing.test.js
https://github.com/eggjs/egg/issues/4418
https://github.com/eggjs/egg/pull/4421
> feat: support enable/disable/clear timing

- .gitignore
- README.md
- lib/utils/timing.js
- test/egg.test.js
- test/fixtures/timing/index.js
- test/fixtures/timing/preload.js
- test/utils/timing.test.js
timing
timing support:
- Process Start: node process start time
- Script Start: js script start time
> feat: timing support Process Start/Script Start

- .github/workflows/nodejs.yml
- README.md
- lib/loader/egg_loader.js
- lib/loader/mixin/config.js
- lib/loader/mixin/router.js
- package.json
- test/fixtures/config-env-app-config/config/config.default.js
- test/fixtures/config-env-app-config/package.json
- test/loader/mixin/load_config.test.js
> feat: support process.env.EGG_APP_CONFIG

- lib/utils/timing.js
- test/egg.test.js
- test/utils/timing.test.js
> fix: should end some timings

- lib/loader/mixin/config.js
> feat: expose set config meta

- lib/loader/mixin/plugin.js
- test/fixtures/plugin-strict/config/config.js
- test/fixtures/plugin-strict/config/plugin.js
- test/fixtures/plugin-strict/package.json
- test/fixtures/plugin-strict/plugins/g/package.json
- test/loader/mixin/load_plugin.test.js
> feat: support plugin strict config

- package.json
https://github.com/eggjs/egg-core/pull/238/files#r902068186
https://github.com/eggjs/egg-core/pull/238/files#r902068186
> chore: update node engines to 8.9.0+

- lib/loader/egg_loader.js
- test/loader/get_app_info.test.js
这是相关的讨论：https://github.com/eggjs/egg/issues/5011
另外，个人觉得在一些涉及多渠道的项目上，明显用scope比env会更适合，希望能早日放到文档上。egg项目的config.default.js，也希望能把scope字段补充上来。
https://github.com/eggjs/egg/blob/master/config/config.default.js#L23
> fix: appInfo.scope no value

- lib/lifecycle.js
- test/egg.test.js
- test/fixtures/timing/app.js
> fix: fix call legacyReadyCallback with options

- .github/workflows/nodejs.yml
- .github/workflows/release.yml
> chore: update workflow to v1

- lib/egg.js
- lib/loader/egg_loader.js
> fix: should support pkg.egg.typescript = true config

- package.json
https://github.com/node-modules/ready-callback/pull/115
> feat: upgrade ready-callback v3
