- README.md
校正英语语法，因为我对这个 Project 不是很了解，可能有的地方会有出入，但希望能够有帮助。请到［这里］（https://github.com/mattma/egg-loader）看看 rendered markdown file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eggjs/egg-loader/7)
> proofread readme documentation and correct english terms

- lib/loader/egg_loader.js
- lib/loader/file_loader.js
- lib/loader/mixin/config.js
- test/fixtures/preload-app-config/config/config.js
- test/loader/mixin/load_config.test.js
loadConfig
app config 里不能取 app config
> fix: can't get appConfig in appConfig

- lib/utils/index.js
- package.json
- test/utils/index.test.js
- [ x ] `npm test` passes
- [ x ] tests and/or benchmarks are included
- [ x ] commit message follows commit guidelines
总是获取当前执行者的用户目录，保证不会权限错乱。当前执行者用户的判断由启动脚本来判断保证。
错乱的场景：`sudo -u admin node app.js`，此时`id -nu`返回的是`admin`。但是`process.env.HOME`并不是admin
> fix: always get the executor's homedir

- lib/loader/egg_loader.js
开源版很多情况下, 都是直接使用 egg 而不是上层框架.
很多人会直接使用 NODE_ENV 而不知道 EGG_SERVER_ENV
因此给个 warning 指引, 后面文档完善后可以修改对应的 url.
> feat: warning when missing EGG_SERVER_ENV at production

- lib/egg.js
- test/egg.test.js
> feat: app.close return a promise

- lib/loader/mixin/extend.js
- test/fixtures/extend-env/app/extend/application.custom.js
- test/fixtures/extend-env/app/extend/application.js
- test/fixtures/extend-env/config/plugin.js
- test/fixtures/extend-env/package.json
- test/fixtures/extend-env/plugins/a/app/extend/application.custom.js
- test/fixtures/extend-env/plugins/a/package.json
- test/loader/mixin/load_extend.test.js
load extend
it's useful when want to export some unittest api
that can't be used in production
> feat: support {env}.js when load extend

- lib/loader/mixin/plugin.js
- test/fixtures/load-plugin-by-env/config/plugin.custom.js
- test/fixtures/load-plugin-by-env/config/plugin.js
- test/fixtures/load-plugin-by-env/config/plugin.unittest.js
- test/fixtures/load-plugin-by-env/package.json
- test/fixtures/load-plugin-by-env/plugins/a/package.json
- test/fixtures/load-plugin-by-env/plugins/b/package.json
- test/fixtures/load-plugin-by-env/plugins/c/package.json
- test/loader/mixin/load_plugin.test.js
load plugin
Control bundle of plugins by env easily
> feat: support plugin.{env}.js

- lib/utils/index.js
- test/utils/index.test.js
Use process.env.EGG_HOME to mock `home`
Ref https://github.com/eggjs/egg/issues/129
> feat: add EGG_HOME to getHomedir for test

- lib/egg.js
- lib/loader/mixin/custom.js
- package.json
- test/fixtures/custom-app-async-function/app.js
- test/fixtures/custom-app-async-function/app.ts
- test/fixtures/custom-app-async-function/package.json
- test/fixtures/custom-app-error/app.js
- test/fixtures/custom-app-error/package.json
- test/fixtures/custom-app-promise/app.js
- test/fixtures/custom-app-promise/package.json
- test/loader/mixin/load_custom_app.test.js
custom app/agent
You can use async function to write async code, never readyCallback.
```js
module.exports = async function(app) {
await doAsync();
};
```
Or use promise wrap on old node
```js
const co = require('co');
module.exports = co.wrap(function* (app) {
yield doAsync();
});
```
Closes eggjs/egg#51
> feat: app.js/agent.js support async function

- lib/utils/router.js
- test/fixtures/router-app/app/router.js
- test/utils/router.test.js
`router.url` 方法替换`/:XX`时并非全局替换，所以在处理多个`/:XX`时会替换失败。给正则添加 global 标识以修复该问题。
> fix: router.url can't parse multi params right

- lib/loader/mixin/plugin.js
- lib/utils/sequencify.js
- test/fixtures/plugin-optional-dependencies/config/plugin.js
- test/fixtures/plugin-optional-dependencies/node_modules/a/package.json
- test/fixtures/plugin-optional-dependencies/node_modules/b/package.json
- test/fixtures/plugin-optional-dependencies/node_modules/c/package.json
- test/fixtures/plugin-optional-dependencies/node_modules/d/package.json
- test/fixtures/plugin-optional-dependencies/node_modules/e/package.json
- test/fixtures/plugin-optional-dependencies/package.json
- test/loader/mixin/load_plugin.test.js
loadPlugin
Closes https://github.com/eggjs/egg/issues/176
> feat: plugin support optionalDependencies

- lib/egg.js
- lib/loader/mixin/router.js
- lib/utils/router.js
- test/fixtures/router-app/app/controller/members.js
- test/fixtures/router-app/app/router.js
- test/utils/router.test.js
- move app API to egg.js from router.js
- use super instead of monkey patch
> refactor: seperate router api from app

- lib/loader/mixin/plugin.js
- test/fixtures/load-plugin-default/config/plugin.default.js
- test/fixtures/load-plugin-default/config/plugin.js
- test/fixtures/load-plugin-default/config/plugin.unittest.js
- test/fixtures/load-plugin-default/package.json
- test/fixtures/load-plugin-default/plugins/a/package.json
- test/fixtures/load-plugin-default/plugins/b/package.json
- test/fixtures/load-plugin-default/plugins/c/package.json
- test/loader/mixin/load_plugin.test.js
- when `plugin.default.js` exist, load it, rather than `plugin.js`, just like `config loader`
- close https://github.com/eggjs/egg/issues/389
> feat: load plugin.default.js rather than plugin.js

- lib/egg.js
- lib/utils/index.js
- test/egg.test.js
- test/fixtures/deprecate/app/extend/application.js
- test/fixtures/deprecate/package.json
增加的损耗：每次调用 deprecate 都需要捕获一次堆栈。
> fix: ensure deprecate display the right call stack

- lib/loader/mixin/extend.js
- test/fixtures/load-plugin-unittest/app/extend/application.local.js
- test/fixtures/load-plugin-unittest/app/extend/application.unittest.js
- test/fixtures/load-plugin-unittest/package.json
- test/loader/mixin/load_extend.test.js
- test/loader/mixin/load_plugin.test.js
loadExtend
When use mm.env, EGG_SERVER_ENV will be changed,
but xx.unittest.js will also be loaded
Closes https://github.com/eggjs/egg/issues/404
> feat: always load extend/xx.unittest.js when run test

- lib/loader/mixin/controller.js
- test/fixtures/controller-app/app/controller/generator_function_ctx.js
- test/fixtures/controller-app/app/controller/number.js
- test/fixtures/controller-app/app/router.js
- test/loader/mixin/load_controller.test.js
closes https://github.com/eggjs/egg/issues/785
> fix: should support module.exports = function*(ctx) {} as a controller

- lib/egg.js
- test/egg.test.js
- test/fixtures/beforestart-with-timeout-env/app.js
- test/fixtures/beforestart-with-timeout-env/package.json
Support app timeout time config, use `EGG_READY_TIMEOUT_ENV = 20000` to config app start get timeout after 20 seconds. Default app ready will get timeout after 10 seconds.
> feat: app timeout support config by env

- lib/loader/mixin/config.js
- test/fixtures/configmeta/config/config.js
- test/loader/mixin/load_config.test.js
bugfix for https://github.com/eggjs/egg-core/pull/106
> fix: should ignore Object.getPrototypeOf check on null/undefined

- lib/loader/mixin/controller.js
- test/fixtures/controller-params/app/controller/class.js
- test/fixtures/controller-params/app/controller/generator_function.js
- test/fixtures/controller-params/app/controller/object.js
- test/fixtures/controller-params/app/router.js
- test/fixtures/controller-params/config/config.default.js
- test/fixtures/controller-params/package.json
- test/loader/mixin/load_controller.test.js
- test/loader/mixin/load_service.test.js
- `app.config.controller.supportParams` to enable
- support return controller's returned value
controller
- controller support params, `app.config.controller.supportParams` to enable
- support return controller's returned value
The only recommended controller format is controller class, generator function is for backward compatibility, `ctx` as the first arguments should be deprecate in the next major version and will be removed in documents.
> feat: controller support params by config

- lib/loader/egg_loader.js
```js
if (this.config.httpclient.enableDNSCache) {
^
TypeError: Cannot read property 'enableDNSCache' of undefined
at Agent.get httpclient [as httpclient] (/Users/jacksontian/git/npp-console/node_modules/.1.7.0@egg/lib/egg.js:246:33)
at abbr (/Users/jacksontian/git/npp-console/node_modules/.1.7.0@egg/lib/egg.js:170:17)
at Agent.inspect (/Users/jacksontian/git/npp-console/node_modules/.1.7.0@egg/lib/egg.js:182:5)
at formatValue (util.js:372:36)
at inspect (util.js:236:10)
at format (util.js:97:24)
at Console.log (console.js:113:24)
at AgentWorkerLoader.EggLoader (/Users/jacksontian/git/npp-console/node_modules/.3.13.0@egg-core/lib/loader/egg_loader.js:34:13)
at AgentWorkerLoader (/Users/jacksontian/git/npp-console/node_modules/.1.7.0@egg/lib/loader/agent_worker_loader.js:9:1)
```
In …
> fix TypeError when DEBUG=*

- lib/loader/mixin/controller.js
- test/fixtures/controller-app/app/controller/class_inherited.js
- test/fixtures/controller-app/app/router.js
- test/loader/mixin/load_controller.test.js
feat(core): adding support to register inherited methods when loading controllers
Closes eggjs/egg#1527
> feat(core): adding support to register inherited methods when loading controllers

- lib/egg.js
- test/egg.test.js
> feat: export app.options

- lib/loader/egg_loader.js
- lib/loader/mixin/plugin.js
- lib/utils/router.js
- lib/utils/sequencify.js
- test/egg.test.js
- test/loader/get_appname.test.js
- test/loader/mixin/load_config.test.js
- test/loader/mixin/load_plugin.test.js
- test/utils/router.test.js
All the subsystems and tests using `indexOf()`.
nodej.s version is 8 / 9 in `.travis.yml` , so I make some changes to make code more readable by using ES6 features. The rules that I used: 
+ replace `indexOf() !== -1` with `includes()`
+ replace `indexOf() >= 0` with `includes()`
+ replace `indexOf() > -1` with `includes()`
+ replace  `indexOf() === -1` with `!includes()`
> styles: replace `indexOf()` with `includes()`

- lib/loader/egg_loader.js
- lib/loader/file_loader.js
- test/egg-ts.test.js
- test/loader/egg_loader.test.js
- test/loader/file_loader.test.js
此前在 fileloader 中，如果 typescript 为 true，并且没有 `require.extensions['.ts']` 的时候，使用 assert 直接抛异常。
但是由于 egg-bin 的配置会在 package.json 中拿 typescript 的配置，因此导致打生产包的时候，想通过 tsc 生成 js 文件，但是此时又 package.json 中 typescript 配置又为 true 的情况下，会导致 egg-mock 实例化出来的 egg 直接因为上面那个 assert 而抛异常。
现在改成 warning，并且 file loader 在设置 match 的时候，只有 typescript 为 true 并且 require.extensions['.ts'] 存在的情况下才会 load ts
> feat: change assert to warning

- README.md
- lib/loader/egg_loader.js
- lib/loader/file_loader.js
- test/egg-ts.test.js
- test/loader/egg_loader.test.js
支持从 env 中读取 typescript 配置，配合 egg-bin 的 https://github.com/eggjs/egg-bin/pull/98 ，从而能够支持在 egg-schedule 等插件中，直接实例化 FileLoader 的时候，也能加载 ts
> feat: support ts by env

- lib/egg.js
- test/egg.test.js
`app.toAsyncFunction()` returns a result that cannot pass `is.asyncFunction()`.
> `is` is [is-type-of](http://web.npm.alibaba-inc.com/package/is-type-of).
> fix: toAsyncFunction can't pass is.asyncFunction()

- .gitignore
- lib/loader/egg_loader.js
- package.json
- test/fixtures/egg/index.js
- test/fixtures/framework-dulp/index.js
- test/fixtures/framework-nosymbol/index.js
- test/fixtures/framework-symbol/node_modules/framework2/index.js
- test/fixtures/framework-wrong-eggpath/index.js
- test/fixtures/run-with-debug/index.js
- test/loader/egg_loader.test.js
- test/utils.js
> fix: Loader can be instantiated without timing

- test/fixtures/extend/app/extend/call.js
- test/loader/mixin/load_extend.test.js
It's not supported by egg, but is introduced from
https://github.com/eggjs/egg-core/pull/156/files#diff-2b53c25bb02c74ba99aee993ad1980baR112
It's a bugfix in #166 rather than a break change
> test: add testcase for loadExtend with function call

- lib/egg.js
- package.json
- test/egg.test.js
1) Change comments for `toPromise` (no need to say with the help of `co`
here but in the document is enough).
2) Add a unit test when the param isn't a function type for
`toAsyncFunction`.
3) Use `--fix` to auto fix the formation when doing eslint's type
checking.
> refactor: toAsyncFunction && toPromise

- lib/loader/file_loader.js
- lib/utils/index.js
- test/egg-ts.test.js
Replace require.extensions with Module._extensions
重构 #188 里的部分实现
**原由**
[beidou](https://github.com/alibaba/beidou) Beidou 2.0版本正在实现 TS的完整支持，[issue](https://github.com/alibaba/beidou/issues/122)。整体方案基于 Babel，不同于egg的 ts-node 模式。
这个模式下，需要对在运行时中 load `.ts` 文件， #188 这个变更，预先读取了 require.extensions，之后在运行时中的 `babel-register` 往 require.extensions 里加钩子，无法让 .ts 加载生效。
看了下变更 PR #188 里的实现，其实是对 Jest 测试的兼容，这里使用 Module._extensions 可以完全达到一样的效果。
Module 读取参考自 [pirates](https://github.com/ariporad/pirates/blob/master/src/index.js#L7)，这也是 babel 依赖的 require hook 包。
- 使用 Module._extensions 替代 require.extensions
> refactor(jest-support): Replace require.extensions with Module._extensions

- .gitignore
- lib/egg.js
- lib/lifecycle.js
- test/loader/file_loader.test.js
**1) For 'gitignore':**
Add the 'package-lock.json' to ignore it.
**2) For 'file_loader.test.js':**
Uncomment one unit test to make full unit test passed.
---
> Chore (gitignore, file_loader.test.js): Update files

- lib/loader/mixin/plugin.js
> fix: don't print when plugins that disabled by app is empty

- .gitignore
- lib/loader/egg_loader.js
- lib/loader/mixin/custom_loader.js
- test/fixtures/custom-loader/app/adapter/docker.js
- test/fixtures/custom-loader/app/controller/user.js
- test/fixtures/custom-loader/app/plugin/a.js
- test/fixtures/custom-loader/app/repository/user.js
- test/fixtures/custom-loader/app/router.js
- test/fixtures/custom-loader/config/b/app/plugin/b.js
- test/fixtures/custom-loader/config/b/package.json
- test/fixtures/custom-loader/config/config.default.js
- test/fixtures/custom-loader/config/plugin.js
- test/fixtures/custom-loader/package.json
- test/loader/mixin/load_custom_loader.test.js
>  feat: add new mixin loadCustomLoader in Loader 

- lib/loader/mixin/plugin.js
- test/fixtures/plugin-duplicate/node_modules/@scope/a/config/config.default.js
- test/fixtures/plugin-duplicate/node_modules/@scope/a/package.json
- test/fixtures/plugin-duplicate/node_modules/@scope/b/config/config.default.js
- test/fixtures/plugin-duplicate/node_modules/@scope/b/package.json
- test/fixtures/plugin-duplicate/node_modules/a/config/config.default.js
- test/fixtures/plugin-duplicate/node_modules/a/package.json
- test/fixtures/plugin-duplicate/release/config/plugin.js
- test/fixtures/plugin-duplicate/release/package.json
- test/loader/mixin/load_plugin.test.js
pnpm 的匹配规则需要作为兜底匹配，顺序放到支持 pnpm 前的 `lookupDirs` 路径列表之后，这样能保持 `egg-core` 的 plugin loader 不会有 break。
> fix: plugin loader

- lib/loader/mixin/plugin.js
- test/loader/mixin/load_plugin.test.js
将几个 plugin 加载逻辑独立出来单独函数，允许上层封装框架在 loader 层面变更插件开关情况。
> 在 Chair 中目前存在根据应用的环境情况，动态开关相关插件的场景，目前只能在 loadPlugin 之后做，导致要手动去篡改 this.plugins 和 this.orderPlugins ，有点不太合理
> feat: add load plugin methods

- lib/loader/mixin/plugin.js
- test/loader/mixin/load_plugin.test.js
对 `getPluginPath()` 的方法进行拆分，以便在 layer 层可以覆盖掉 resolve 的逻辑。
解决 https://github.com/eggjs/egg-core/pull/238 对我们 layer 模式带来的影响。
在 Layer 层用这段逻辑覆盖回去：https://github.com/eggjs/egg-core/blob/4.22.0/lib/loader/mixin/plugin.js#L358
> feat: extract plugin loader method for override

- lib/loader/mixin/plugin.js
- test/loader/mixin/load_plugin.test.js
**note: `dependents` will not includes `optionalDependencies`**
**note: `dependents` will not includes `optionalDependencies`**
**note: `dependents` will not includes `optionalDependencies`**
> feat: dump plugin info when it implicit enable by dependents plugin

- .github/workflows/nodejs.yml
- benchmark/middleware/README.md
- lib/egg.js
- lib/lifecycle.js
- lib/utils/timing.js
- package.json
- test/asyncLocalStorage.test.js
- test/egg.test.js
- test/fixtures/egg/app/middleware/status.js
- test/fixtures/egg/node_modules/session/app.js
- test/fixtures/session-cache-app/app/controller/home.js
- test/fixtures/session-cache-app/app/router.js
- test/fixtures/session-cache-app/package.json
- test/loader/mixin/load_middleware.test.js
https://github.com/koajs/koa/pull/1721
> feat: enable asyncLocalStorage by default

- index.d.ts
- lib/egg.js
- lib/loader/egg_loader.js
- package.json
> feat: auto register tsconfig-paths on env.EGG_TYPESCRIPT enable

- package.json
index.d.ts dependency on them
```ts
import KoaApplication = require('koa');
import depd = require('depd');
```
> fix: @types/depd and @types/koa should be dependencies

- lib/utils/timing.js
- package.json
- test/egg.test.js
- test/utils/timing.test.js
```bash
egg start timeline:
▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ [289ms] - #0 Process Start
▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ [510ms] - #1 Application Start
▇ [2ms] - #2 Load Plugin
▇ [1ms] - #3 Load Config
▇ [0ms] - #4 Require(0) ~/eggjs/egg-core/test/fixtures/egg/config/config.default.js
▇ [0ms] - #5 Require(1) ~/eggjs/egg-core/test/fixtures/egg/config/config.unittest.js
▇ [0ms] - #6 Load extend/application.js
▇ [0ms] - #7 Require(2) ~/eggjs/egg-core/test/fixtures/egg/app/extend/application.js
▇ [1ms] - #8 Load extend/context.js
▇ [0ms] - #9 Load extend/request.js
▇ [0ms] - #10 Load extend/response.js
▇ [1ms] - #11 Load app.js
▇ [0ms] - #12 Require(3) ~/eggjs/egg-core/test/fixtures/egg/node_modules/session/app.js
▇ [0ms] - #13 Require(4) app.js
▇▇▇▇▇▇ [101ms] - #14 readyCallback in a …
```
> feat: support show app.timing in timline string

- .github/workflows/release.yml
- lib/egg.js
- test/asyncLocalStorage.test.js
- test/loader/mixin/load_middleware.test.js
closes https://github.com/eggjs/egg/issues/5271
> feat: export asyncLocalStorage instance to global

- lib/egg.js
- package.json
- test/asyncLocalStorage.test.js
https://github.com/node-modules/gals
> fix: use gals lib

- .github/workflows/nodejs-5.x.yml
- .github/workflows/release-5.x.yml
- .gitignore
- README.md
- lib/egg.js
- lib/loader/mixin/middleware.js
- package.json
- test/fixtures/router-app-with-pathToRegexpModule/app/controller/async.js
- test/fixtures/router-app-with-pathToRegexpModule/app/controller/comments.js
- test/fixtures/router-app-with-pathToRegexpModule/app/controller/locals.js
- test/fixtures/router-app-with-pathToRegexpModule/app/controller/members.js
- test/fixtures/router-app-with-pathToRegexpModule/app/controller/middleware.js
- test/fixtures/router-app-with-pathToRegexpModule/app/controller/package.js
- test/fixtures/router-app-with-pathToRegexpModule/app/controller/posts.js
- test/fixtures/router-app-with-pathToRegexpModule/app/middleware/async.js
- test/fixtures/router-app-with-pathToRegexpModule/app/middleware/common.js
- test/fixtures/router-app-with-pathToRegexpModule/app/middleware/generator.js
- test/fixtures/router-app-with-pathToRegexpModule/app/middleware/generator_both.js
- test/fixtures/router-app-with-pathToRegexpModule/app/router.js
- test/fixtures/router-app-with-pathToRegexpModule/app/views/locals/router.html
- test/fixtures/router-app-with-pathToRegexpModule/config/config.default.js
- test/fixtures/router-app-with-pathToRegexpModule/package.json
- test/utils/router-with-pathToRegexpModule.test.js
deps on
- https://github.com/eggjs/router/pull/18
- https://github.com/eggjs/egg-path-matching/pull/11
> feat: support custom pathToRegexpModule on app.options

- package.json
- src/egg.ts
- src/loader/file_loader.ts
- src/utils/index.ts
- test/egg-ts.test.ts
and export router context extend
> feat: support vitest
